# Generated by Django 4.2.4 on 2023-12-13 14:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the bakery', max_length=200)),
                ('address', models.CharField(blank=True, help_text='Address of the bakery', max_length=500, null=True)),
                ('is_open', models.BooleanField(default=True, help_text='Whether the store is currently open')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='StoreHours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Day of week should be between 1 and 7.'), django.core.validators.MaxValueValidator(7, message='Day of week should be between 1 and 7.')])),
                ('opens', models.TimeField()),
                ('closes', models.TimeField()),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
            ],
        ),
    ]
